/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainPackage_NativeClass */

#ifndef _Included_mainPackage_NativeClass
#define _Included_mainPackage_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainPackage_NativeClass
 * Method:    izvrsiUpit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mainPackage_NativeClass_izvrsiUpit
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
